modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "directionalaudioremastered"
displayName = "Directional Audio Remastered"
version = "${version}"
displayURL = ""
logoFile = "assets/icon.png"
authors = "VesMaybeVesper"
description = '''Minecraft's directional audio setting, but good'''

[[mixins]]
config = "modtemplate.mixins.json"

[[dependencies.directionalaudioremastered]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.directionalaudioremastered]]
modId = "minecraft"
type = "required"
